# To fetch schema from
introspection: https://staging.agitron.dev/api
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImRhcmtvIiwiZW1haWwiOiJkYXJrb0BhZ2l0cm9uLmlvIiwiZG9tYWluIjoic3RhZ2luZyJ9LCJpYXQiOjE2MDU1MTk3ODEsImV4cCI6MTYwNTUyMTU4MX0.k2SgQ5bSTa95GGGr_SMEWGtRUhltcqdCWA_0BJ9XU7I
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImRhcmtvIiwiZW1haWwiOiJkYXJrb0BhZ2l0cm9uLmlvIiwiZG9tYWluIjoic3RhZ2luZyJ9LCJpYXQiOjE2MDU1MTk3ODEsImV4cCI6MTYwNjEyNDU4MX0.7ZJMinase0dbWHGPK2Z7W4VHUoSUjJYpy6e2DVj7E6U
servers: # same format as for OpenAPI Specification
  - url: https://agitron.dev
    description: Dev
  - url: https://agitron.app
    description: Prod

info: # same format as for OpenAPI Specification
    title: Agitron GraphQL API
    description: Description    

 # define your domains by providing a set of usecases
domains:
  - name: User # Name of the domain
    description: Description  # Description of the domain
    usecases:         
     - name: Login Mutation # Mutation 
       description: Users can login with this mutation
       query: mutation.login # Mutation example - invoke mutation
       expand: addedProducts(id)
  - name: Products # Name of the domain
    description: Description  # Description of the domain
    usecases:         
     - name: AddEdit Products Mutation # Mutation 
       description: AddEdit Products
       query: mutation.addEditProducts # Mutation example - invoke mutation
